#!/usr/bin/env python3
"""
make_dag.py - build the probe jobs and a DAG that runs them.

Each job.sub is assembled from three readable pieces:
    common.sub  +  sites/<site>.sub  +  tests/<test>.sub
and written to runs/<tag>/<site>/<test>/job.sub, together with meta.json
(the test's question) and, for tests that need an eviction, trigger.sub.

Test files carry directives in comments:
    # @question: ...            what the test answers
    # @sites: chtc ospool       sites it applies to
    # @triggers: vacate:150     one job per trigger, fired N seconds after the first start
    # @variants: bare           also run without the container (CHTC sites only)
    # @optin                    only built when named in --optin

REQUIRED first: tell it where your /staging directory is (no personal path is stored in the repo):
    export PROBE_STAGING_DIR=/staging/<username>     # or pass --staging-dir each time

Examples (run on ap2002, from this directory):
    python3 make_dag.py --list
    python3 make_dag.py --sites chtc --tests P0,P1 --check
    python3 make_dag.py --sites chtc,ospool
    python3 make_dag.py --sites chtc_backfill --triggers vacate --no-bare   # GPU: keep it small
    condor_submit_dag runs/<tag>/probes.dag
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SITES = ["chtc", "chtc_gpu", "chtc_backfill", "ospool"]


def parse_test(path):
    meta = {"name": os.path.basename(path)[:-4], "question": "", "sites": [], "triggers": [],
            "variants": [], "optin": False}
    with open(path) as f:
        text = f.read()
    for m in re.finditer(r"^# @(\w+):?(.*)$", text, re.M):
        key, val = m.group(1), m.group(2).strip()
        if key == "question":
            meta["question"] = val
        elif key == "sites":
            meta["sites"] = val.split()
        elif key == "triggers":
            for tok in val.split():
                action, after = tok.split(":")
                meta["triggers"].append({"action": action, "after": int(after)})
        elif key == "variants":
            meta["variants"] = val.split()
        elif key == "optin":
            meta["optin"] = True
    meta["body"] = text
    return meta


def load_tests():
    tdir = os.path.join(HERE, "tests")
    return [parse_test(os.path.join(tdir, f)) for f in sorted(os.listdir(tdir)) if f.endswith(".sub")]


def strip_container(text):
    return "\n".join(l for l in text.splitlines() if not l.strip().startswith("container_image"))


def build_submit(test_name, site, test, bare, staging_dir):
    with open(os.path.join(HERE, "common.sub")) as f:
        common = f.read()
    with open(os.path.join(HERE, "sites", site + ".sub")) as f:
        site_text = f.read()
    body = test["body"]
    if bare:
        site_text, body = strip_container(site_text), strip_container(body)
    return "\n".join([
        "# GENERATED by make_dag.py on %s - edit common.sub, sites/%s.sub or tests/%s.sub instead."
        % (time.strftime("%Y-%m-%d %H:%M"), site, test["name"]),
        "PROBES    = " + HERE,
        "STAGING_DIR = " + staging_dir,
        "TEST_NAME = " + test_name,
        "SITE      = " + site,
        "", "# ----- common.sub -----", common,
        "# ----- sites/%s.sub%s -----" % (site, " (container lines removed: bare variant)" if bare else ""),
        site_text,
        "# ----- tests/%s.sub -----" % test["name"], body,
        "# ----- assembled by make_dag.py -----",
        "requirements = $(SITE_REQS) && $(TEST_REQS)",
        "queue", "",
    ])


def build_trigger_submit(job_dir, trig, condor_bin):
    args = [os.path.join(HERE, "trigger.py"), "--log", os.path.join(job_dir, "job.log"),
            "--action", trig["action"], "--after", str(trig["after"]),
            "--out", os.path.join(job_dir, "trigger.jsonl")]
    if condor_bin:
        args += ["--condor-bin", condor_bin]
    return "\n".join([
        "# GENERATED by make_dag.py. Runs trigger.py on the access point (local universe).",
        "# It reads job.log every 15 s (no condor_q) and fires the eviction once.",
        "universe            = local",
        "executable          = " + sys.executable,
        'arguments           = "%s"' % " ".join(args),
        "transfer_executable = false",
        "output              = trigger.stdout",
        "error               = trigger.stderr",
        "log                 = trigger_node.log",
        "queue", "",
    ])


def condor_dry_run(job_dir):
    """Ask condor_submit to parse the file without submitting it."""
    try:
        p = subprocess.Popen(["condor_submit", "-dry-run", os.devnull, "job.sub"], cwd=job_dir,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        out, _ = p.communicate(timeout=60)
        return p.returncode, out.decode(errors="replace")
    except Exception as e:
        return -1, str(e)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sites", default="chtc", help="comma list from: " + ", ".join(SITES))
    ap.add_argument("--tests", default="", help="comma list of name prefixes, e.g. P0,P2a,P3 (default: all)")
    ap.add_argument("--optin", default="", help="comma list of opt-in test prefixes to include, e.g. P3e,P5b")
    ap.add_argument("--tag", default=time.strftime("%Y%m%d-%H%M%S"), help="run name (default: timestamp)")
    ap.add_argument("--maxjobs", type=int, default=4, help="probe jobs in the queue at once")
    ap.add_argument("--no-trigger-nodes", action="store_true",
                    help="if the AP forbids local-universe jobs: leave triggers out of the DAG and "
                         "write run_triggers.sh to run them by hand under nohup/tmux")
    ap.add_argument("--check", action="store_true",
                    help="run condor_submit -dry-run on each job; leave rejected ones out of the DAG")
    ap.add_argument("--triggers", default="",
                    help="only build these trigger variants, e.g. vacate (default: all). Tests without "
                         "a trigger are always built")
    ap.add_argument("--no-bare", action="store_true", help="skip the bare (no container) variants")
    ap.add_argument("--staging-dir", default=os.environ.get("PROBE_STAGING_DIR", ""),
                    help="your /staging directory, e.g. /staging/<user> (default: $PROBE_STAGING_DIR)")
    ap.add_argument("--list", action="store_true", help="list tests and exit")
    args = ap.parse_args()

    tests = load_tests()
    if args.list:
        for t in tests:
            trig = ", ".join("%s@%ds" % (x["action"], x["after"]) for x in t["triggers"]) or "-"
            print("%-28s sites=%-36s triggers=%-40s%s%s" % (
                t["name"], ",".join(t["sites"]), trig, " +bare" if "bare" in t["variants"] else "",
                " OPT-IN" if t["optin"] else ""))
            print("    " + t["question"])
        return

    staging_dir = args.staging_dir.rstrip("/")
    if not staging_dir.startswith("/staging/"):
        sys.exit("ERROR: PROBE_STAGING_DIR is not set (or not under /staging/).\n"
                 "       Run:  export PROBE_STAGING_DIR=/staging/<username>\n"
                 "       (add it to ~/.bashrc on the access point), or pass --staging-dir /staging/<username>")
    sites = [s for s in args.sites.split(",") if s]
    for s in sites:
        if s not in SITES:
            sys.exit("unknown site %r (choose from %s)" % (s, ", ".join(SITES)))
    wanted = [p for p in args.tests.split(",") if p]
    optin = [p for p in args.optin.split(",") if p]
    only_triggers = [p for p in args.triggers.split(",") if p]
    condor_bin = os.path.dirname(shutil.which("condor_vacate_job") or "")

    run_dir = os.path.join(HERE, "runs", args.tag)
    if os.path.exists(run_dir):
        sys.exit("%s already exists; pick another --tag" % run_dir)
    os.makedirs(run_dir)

    dag = ["# GENERATED by make_dag.py --sites %s --tests %s --optin %s"
           % (args.sites, args.tests or "(all)", args.optin or "(none)"),
           "# Submit with:  condor_submit_dag %s" % os.path.join(run_dir, "probes.dag"), ""]
    manual_triggers = []
    built, rejected = [], []

    for site in sites:
        for t in tests:
            if site not in t["sites"]:
                continue
            if wanted and not any(t["name"].startswith(p) for p in wanted):
                continue
            if t["optin"] and not any(t["name"].startswith(p) for p in optin):
                continue
            bare_options = [False] + ([True] if "bare" in t["variants"] and site.startswith("chtc")
                                      and not args.no_bare else [])
            trig_options = [x for x in t["triggers"] if not only_triggers or x["action"] in only_triggers]
            if t["triggers"] and not trig_options:
                continue
            for bare in bare_options:
                for trig in (trig_options or [None]):
                    name = t["name"] + ("-bare" if bare else "") + ("-" + trig["action"] if trig else "")
                    job_dir = os.path.join(run_dir, site, name)
                    os.makedirs(job_dir)
                    with open(os.path.join(job_dir, "job.sub"), "w") as f:
                        f.write(build_submit(name, site, t, bare, staging_dir))
                    meta = {"test": name, "base_test": t["name"], "site": site, "bare": bare,
                            "question": t["question"], "trigger": trig, "tag": args.tag}
                    if args.check:
                        rc, out = condor_dry_run(job_dir)
                        meta["dry_run_rc"], meta["dry_run_output"] = rc, out[-2000:]
                        if rc != 0:
                            rejected.append((site, name, out.strip().splitlines()[-1:] or [""]))
                            with open(os.path.join(job_dir, "meta.json"), "w") as f:
                                json.dump(meta, f, indent=2)
                            continue
                    with open(os.path.join(job_dir, "meta.json"), "w") as f:
                        json.dump(meta, f, indent=2)

                    node = "%s__%s" % (site, name)
                    dag += ["JOB %s %s DIR %s" % (node, "job.sub", job_dir),
                            "CATEGORY %s probes" % node,
                            "SCRIPT POST %s %s %s --test-dir %s --job-id $JOBID"
                            % (node, sys.executable, os.path.join(HERE, "analyze.py"), job_dir)]
                    if trig:
                        with open(os.path.join(job_dir, "trigger.sub"), "w") as f:
                            f.write(build_trigger_submit(job_dir, trig, condor_bin))
                        if args.no_trigger_nodes:
                            manual_triggers.append((job_dir, trig))
                        else:
                            dag.append("JOB %s__trigger trigger.sub DIR %s" % (node, job_dir))
                    dag.append("")
                    built.append((site, name))

    dag += ["MAXJOBS probes %d" % args.maxjobs, ""]
    with open(os.path.join(run_dir, "summary.sub"), "w") as f:
        f.write("\n".join([
            "# GENERATED by make_dag.py. Writes results/%s/summary.md on the access point." % args.tag,
            "universe            = local",
            "executable          = " + sys.executable,
            'arguments           = "%s --summary --run-dir %s"' % (os.path.join(HERE, "analyze.py"), run_dir),
            "transfer_executable = false",
            "output = summary.stdout", "error = summary.stderr", "log = summary_node.log",
            "queue", ""]))
    if not args.no_trigger_nodes:
        dag.append("FINAL summary summary.sub DIR %s" % run_dir)
    with open(os.path.join(run_dir, "probes.dag"), "w") as f:
        f.write("\n".join(dag) + "\n")

    if manual_triggers:
        lines = ["#!/bin/bash",
                 "# Run on the AP right after condor_submit_dag, e.g. inside tmux or with:",
                 "#   nohup bash %s > %s 2>&1 &" % (os.path.join(run_dir, "run_triggers.sh"),
                                                   os.path.join(run_dir, "run_triggers.log")),
                 "# Each trigger only reads its job's event log every 15 s (no condor_q).", ""]
        for job_dir, trig in manual_triggers:
            lines.append("%s %s --log %s/job.log --action %s --after %d --out %s/trigger.jsonl &"
                         % (sys.executable, os.path.join(HERE, "trigger.py"), job_dir,
                            trig["action"], trig["after"], job_dir))
        lines += ["wait", "%s %s --summary --run-dir %s" % (sys.executable, os.path.join(HERE, "analyze.py"), run_dir), ""]
        with open(os.path.join(run_dir, "run_triggers.sh"), "w") as f:
            f.write("\n".join(lines))

    print("Built %d probe jobs in %s" % (len(built), run_dir))
    for site, name in built:
        print("  %-14s %s" % (site, name))
    if rejected:
        print("\ncondor_submit -dry-run REJECTED these (left out of the DAG; see meta.json):")
        for site, name, last in rejected:
            print("  %-14s %-34s %s" % (site, name, last[0][:100] if last else ""))
    print("\nNext:  condor_submit_dag %s" % os.path.join(run_dir, "probes.dag"))
    if manual_triggers:
        print("Then:  nohup bash %s > %s 2>&1 &" % (os.path.join(run_dir, "run_triggers.sh"),
                                                    os.path.join(run_dir, "run_triggers.log")))


if __name__ == "__main__":
    main()
